/* Generated by tex3ds */
#pragma once

#define boss_splash_atlas_portrait_gemini_idx 0
#define boss_splash_atlas_portrait_larry_idx 1
#define boss_splash_atlas_portrait_famine_idx 2
#define boss_splash_atlas_portrait_peep_idx 3
#define boss_splash_atlas_portrait_gurdy_idx 4
#define boss_splash_atlas_name_gemini_idx 5
#define boss_splash_atlas_name_larry_idx 6
#define boss_splash_atlas_name_famine_idx 7
#define boss_splash_atlas_name_peep_idx 8
#define boss_splash_atlas_name_gurdy_idx 9
