/* Generated by tex3ds */
#pragma once

#define menu_text_atlas_menu_newrun_idx 0
#define menu_text_atlas_menu_continue_idx 1
#define menu_text_atlas_menu_challenges_idx 2
#define menu_text_atlas_menu_stats_idx 3
#define menu_text_atlas_menu_options_idx 4
#define menu_text_atlas_menu_continue_gray_idx 5
#define menu_text_atlas_menu_arrow_idx 6
