/* Generated by tex3ds - updated with 12 new enemy sprites */
#pragma once

/* Player walk animations (head+body composed from official sheet) */
#define sprites_atlas_player_down_idx 0
#define sprites_atlas_player_down2_idx 1
#define sprites_atlas_player_up_idx 2
#define sprites_atlas_player_up2_idx 3
#define sprites_atlas_player_left_idx 4
#define sprites_atlas_player_left2_idx 5
#define sprites_atlas_player_right_idx 6
#define sprites_atlas_player_right2_idx 7

/* Player shooting poses (crying head + body) */
#define sprites_atlas_player_shoot_down_idx 8
#define sprites_atlas_player_shoot_up_idx 9
#define sprites_atlas_player_shoot_left_idx 10
#define sprites_atlas_player_shoot_right_idx 11

/* Player special states */
#define sprites_atlas_player_hurt_idx 12
#define sprites_atlas_player_pickup_idx 13
#define sprites_atlas_player_death_idx 14

/* Original Enemies */
#define sprites_atlas_enemy_fly_idx 15
#define sprites_atlas_enemy_gaper_idx 16
#define sprites_atlas_enemy_pacer_idx 17
#define sprites_atlas_enemy_spider_idx 18
#define sprites_atlas_enemy_clotty_idx 19

/* New Enemies (12 types) */
#define sprites_atlas_enemy_attack_fly_idx 20
#define sprites_atlas_enemy_pooter_idx 21
#define sprites_atlas_enemy_hopper_idx 22
#define sprites_atlas_enemy_baby_idx 23
#define sprites_atlas_enemy_globin_idx 24
#define sprites_atlas_enemy_boom_fly_idx 25
#define sprites_atlas_enemy_maw_idx 26
#define sprites_atlas_enemy_mulligan_idx 27
#define sprites_atlas_enemy_host_idx 28
#define sprites_atlas_enemy_red_maw_idx 29
#define sprites_atlas_enemy_leaper_idx 30
#define sprites_atlas_enemy_vis_idx 31

/* Bosses */
#define sprites_atlas_boss_duke_of_flies_idx 32
#define sprites_atlas_boss_monstro_idx 33
#define sprites_atlas_boss_gemini_idx 34
#define sprites_atlas_boss_larry_jr_idx 35
#define sprites_atlas_boss_famine_idx 36

/* Projectiles & Effects */
#define sprites_atlas_projectile_tear_idx 37
#define sprites_atlas_effect_blood_1_idx 38
#define sprites_atlas_effect_blood_2_idx 39
#define sprites_atlas_effect_explosion_idx 40